/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Center: typeof import('./src/components/center.vue')['default']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FaMenXiJie: typeof import('./src/components/FaMenXiJie/index.vue')['default']
    JinRiBaoJing: typeof import('./src/components/JinRiBaoJing/index.vue')['default']
    NongDuXiJie: typeof import('./src/components/NongDuXiJie/index.vue')['default']
    Officereview: typeof import('./src/components/officereview.vue')['default']
    RenTiXiJie: typeof import('./src/components/RenTiXiJie/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/ReIcon/src/Select.vue')['default']
    Tufour: typeof import('./src/components/tufour/index.vue')['default']
    Tuone: typeof import('./src/components/tuone/index.vue')['default']
    Tuthree: typeof import('./src/components/tuthree/index.vue')['default']
    Tutwo: typeof import('./src/components/tutwo/index.vue')['default']
    XiJie: typeof import('./src/components/XiJie/index.vue')['default']
    XinDianEchart: typeof import('./src/components/XinDianEchart/index.vue')['default']
    ZhongXinCeShuJuHuiZong: typeof import('./src/components/ZhongXinCeShuJuHuiZong/index.vue')['default']
  }
}
